### ISSUE TITLE
最终配速

### ISSUE THREAD

**Issue by haishe0** [kontori/yun#1]
您好，想问一下，该如何修改代码，才可以更改最终的配速？

**Comment by kontori** [comment]
最终配速是由`总时间/总公里数`得到，即最终的`recodePace`字段，不应手动更改。而预估耗时是由高德地图api返回，累计相加得到`now_time`总耗时。也就是说，如果你想要更改最终配速，修改now_time计算方式即可。

**Comment by haishe0** [comment]
源代码：self.now_time += path['duration']
修改为：self.now_time += 2*path['duration']
即可更改总时间，此配速最总在8左右

再完善就是
源代码：self.now_time = 0
将此行代码的self.now_time在一定范围内取一定的随机例如，在[-10,10]之间随机取一个整数，即可使总时间有一个波动，从而使得，配速也产生波动，最总配速6-12之间。

**Comment by kontori** [comment]
是的，这部分你可以自行完善。但注意，男生最终配速6.0、女生最终配速7.0以内才算是满分哦
