### ISSUE TITLE
跑步范围

### ISSUE THREAD

**Issue by haishe0** [kontori/yun#3]
抱歉，又来打扰了，对于新的代码存在一个问题，就是跑步过程中会出现跑出学校的情况，想问一下，应如何进行约束，只在校内进行跑步（因为特殊情况现在不可能出现：运动范围超出学校的）

**Comment by kontori** [comment]
对于这个，只能说很难处理；你可以拉一下最新的代码，尝试把跑出学校的点排除，或限制超出公里数（一般如果跑出学校，公里数都会超出很多）。其实我一开始是想写一个GUI的，手动描路径就直接避免了这个问题，但现在实在懒得改了orz
